/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { webController } from '../entryability/EntryAbility';

@Entry
@Component
struct Index {
  @StorageProp('systemLanguage') language: string = '';

  build() {
    Column() {
      Web({
        src: $rawfile('index.html'),
        controller: webController
      })
        .expandSafeArea([SafeAreaType.SYSTEM])
        .zoomAccess(false)
    }
    .width('100%')
    .height('100%')
    .backgroundColor('#F1F3F5')
    .expandSafeArea([SafeAreaType.SYSTEM])
  }
}